USE [AvaleoAnalytics_STA]
GO

/****** Object:  UserDefinedFunction [dbo].[Udf_SaetDoegninddeling]    Script Date: 12/28/2010 10:01:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date, ,>
-- Description:	<Description, ,>
-- =============================================
CREATE FUNCTION [dbo].[Udf_SaetDoegninddeling]  
(
	@MINUTTEREFTERMIDNAT as smallint
)
RETURNS int

AS

BEGIN
declare @RESULT as int
set @RESULT = 0
	IF @MINUTTEREFTERMIDNAT> 420 and @MINUTTEREFTERMIDNAT <= 540 SET @RESULT = 1 
    ELSE IF @MINUTTEREFTERMIDNAT > 540 and @MINUTTEREFTERMIDNAT<= 660 SET @RESULT = 2 
    ELSE IF  @MINUTTEREFTERMIDNAT > 660 and @MINUTTEREFTERMIDNAT <= 780 SET @RESULT = 3 
	ELSE IF  @MINUTTEREFTERMIDNAT > 780 and @MINUTTEREFTERMIDNAT <= 900 SET @RESULT = 4 
	ELSE IF  @MINUTTEREFTERMIDNAT > 900 and @MINUTTEREFTERMIDNAT <= 1020 SET @RESULT = 5 
	ELSE IF  @MINUTTEREFTERMIDNAT > 1020 and @MINUTTEREFTERMIDNAT <= 1140 SET @RESULT = 6 
	ELSE IF  @MINUTTEREFTERMIDNAT > 1140 and @MINUTTEREFTERMIDNAT <= 1260 SET @RESULT = 7 
	ELSE IF  @MINUTTEREFTERMIDNAT > 1260 and @MINUTTEREFTERMIDNAT <= 1380 SET @RESULT = 8 
	ELSE IF  @MINUTTEREFTERMIDNAT > 1380 and @MINUTTEREFTERMIDNAT <= 1440 OR @MINUTTEREFTERMIDNAT <= 60 SET @RESULT = 9 
	ELSE IF  @MINUTTEREFTERMIDNAT> 60 and @MINUTTEREFTERMIDNAT <= 180 SET @RESULT = 10 
	ELSE IF  @MINUTTEREFTERMIDNAT > 180 and @MINUTTEREFTERMIDNAT <= 300 SET @RESULT = 11 
	ELSE IF  @MINUTTEREFTERMIDNAT > 300 and @MINUTTEREFTERMIDNAT <= 420 SET @RESULT = 12 
  RETURN @RESULT	
END


GO

declare @version as int
set @version = (SELECT VERSION FROM AvaleoAnalytics_DW.dbo.VERSION WHERE VERSION=2)
if @version is null
begin
INSERT INTO AvaleoAnalytics_DW.[dbo].[VERSION] ([VERSION],[OPDATERINGSDATO])
VALUES (2,GETDATE())           
end


