USE [AvaleoAnalytics_STA]
GO

/****** Object:  View [dbo].[Dim_jobtyper]    Script Date: 11/26/2010 07:50:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER VIEW [dbo].[Dim_jobtyper]
AS
SELECT     JOBID, JOBNAVN, KATEGORI, NIVEAU1, NIVEAU2, NIVEAU3, SLETTET_JOB, SKRIVEBESKYTTET, FALLES_SPROG_KAT_KODE, 
                      FALLES_SPROG_NIV1_KODE, FALLES_SPROG_NIV2_KODE, FALLES_SPROG_NIV3_KODE, SIDSTE_VITALE_AENDRING, PLEJETYPE, NORMTID2, 
                      NORMTID3, NORMTID4, FUNKKAT, MAXTID2, MAXTID3, MAXTID4, FALLES_SPROG_ART, PARAGRAF, NORMTID1, MAXTID1, BTP
FROM         JOBTYPER
GO

declare @version as int
set @version = (SELECT VERSION FROM AvaleoAnalytics_DW.dbo.VERSION WHERE VERSION=5)
if @version is null
begin
INSERT INTO AvaleoAnalytics_DW.[dbo].[VERSION] ([VERSION],[OPDATERINGSDATO])
VALUES (5,GETDATE())           
end

